### ISSUE TITLE
deprecated: transaction.commit_on_success()

### ISSUE THREAD

**Issue by f403** [ramusus/django-vkontakte-api#13]
transaction.commit_on_success() is deprecated since Django 1.6 and not supported since 1.8
This affects also django-vkontakte-wall, django-vkontakte-users, django-vkontakte-comments, etc.

**Comment by ramusus** [comment]
I submitted new versions, which should solve this problem

**Comment by f403** [comment]
Теперь хуже стало, сорри (я с Джанго почти не знаком).

```python
user = User.remote.fetch()[0]
posts = user.fetch_posts()
post = posts[2]
post.fetch_comments()
```
Ругается *This is forbidden when an 'atomic' block is active.* на последней строке.

**Comment by ramusus** [comment]
какая версия django ?
